### ISSUE TITLE
Query network without bootnodes

### ISSUE THREAD

**Issue by Ali-Usama** [lexnv/subp2p-explorer#1]
Is providing the boot-nodes necessary to query the network? Or is there any other way too e.g. using Kademlia random walk like [here](https://github.com/paritytech/polkadot-sdk/blob/e5b2adac7ad5c44f0231af808e18258f4599c882/substrate/client/network/src/discovery.rs#L173)

**Comment by lexnv** [comment]
The boot-nodes are necessary at the moment. As a client, we'd need to know at least one node to further discover the network; via the DHT discovery mechanism. [This](https://github.com/lexnv/subp2p-explorer/blob/main/cli/src/commands/discovery.rs#L55) file of the CLI example of this repo is randomly walking the DHT.

How this works at a high level:
- client establishes a connection to the bootnode
- then performs a DHT query to ask the bootnode to give K=20 closest peers to a given address

The `DiscoveryConfig` pointed in the link provides a way to construct a `DiscoveryBehavior`. This is then part of the network behavior of the libp2p on substrate based chains [here](https://github.com/paritytech/polkadot-sdk/blob/e5b2adac7ad5c44f0231af808e18258f4599c882/substrate/client/network/src/behaviour.rs#L44-L57). Substrate has a field in the `NetworkConfig`, named `boot_nodes`; which ensures the node can reach the network by provided list of bootnodes.

**Comment by Ali-Usama** [comment]
Basically, what I want is to use Kademlia for discovery/routing, and connect my network with the IPFS network. I have read at a stackexchange question that I would have to use a protocol name for my DHT, e.g. using [`<genesis-hash>/kad`](https://github.com/paritytech/polkadot-sdk/blob/e5b2adac7ad5c44f0231af808e18258f4599c882/substrate/client/network/src/discovery.rs#L935) as a protocol name forces Kademlia to only connect to the Polkadot nodes. This was the reason for sharing [this](https://github.com/paritytech/polkadot-sdk/blob/e5b2adac7ad5c44f0231af808e18258f4599c882/substrate/client/network/src/discovery.rs#L173) link in the issue statement that I thought this makes it possible for the Polkadot network to make use of Kademlia to connect to IPFS, and whether it will be possible using this CLI tool. 

Do you have any suggestions for it, i.e. connecting my network to IPFS and then querying the nodes from the IPFS network using a `protocol-id` instead of providing any bootnodes?

**Comment by lexnv** [comment]
I see what you mean now! Thanks for sharing more info!

The intention behind this project was to provide tools for the p2p network of substrate-based chains. Because of that, several places in the code are opinionated.

The easiest thing you could do to test this, would be to replace the `kademlia_protocols` with a `StreamProtocol` that reflects the IPFS (`/ipfs/kad/1.0.0`):
https://github.com/lexnv/subp2p-explorer/blob/8f99d9bf5126e0d2c353f401272d04cef4b5b5f2/subp2p-explorer/src/discovery.rs#L77-L81



How I would approach this as a first step to make Kademlia protocol name generic: 
- Replace the discovery builder's genesis parameter with `kademlia_protocols: Vec<StreamProtocol>`

https://github.com/lexnv/subp2p-explorer/blob/8f99d9bf5126e0d2c353f401272d04cef4b5b5f2/subp2p-explorer/src/discovery.rs#L69-L82

- Add a similar function for building the `build_swarm_with_protocols(genesis: String, bootnodes: Vec<String>, protocols: Vec<StreamProtocol>)` 

https://github.com/lexnv/subp2p-explorer/blob/8f99d9bf5126e0d2c353f401272d04cef4b5b5f2/cli/src/utils.rs#L75-L78

- Reuse the `build_swarm_with_protocols` for `build_swarm` with opinionated `genesis/kad`

Let me know if you'd like to tackle that, or any approach you might think is better and create a PR! 


> Do you have any suggestions for it, i.e. connecting my network to IPFS and then querying the nodes from the IPFS network using a protocol-id instead of providing any bootnodes?

To my knowledge, connecting to a network requires you to know at least one other peer. The protocol-id is a unique identifier (for substrate-kad is `genesis/kad`) that peers communicate with each other to specify which functionality they want from each other

**Comment by lexnv** [comment]
I'll close the issue for now, let me know if you'd need further help with this 🙏
